import PythonTurtle
t=turtle.Turtle()
turtle.bgcolor('black')
t.begin_fill()
t.fillcolor('yellow')
t.left(140)
t.forward(180)
t.circle(-90,203)
t.end_fill()
t.up()
t.home()
t.down()
t.begin_fill()
t.fillcolor('green')
t.setheading(40)
t.fd(180)
t.circle(90,204)
t.end_fill()
t.end_fill()
t.up()
t.home()
t.goto(0,150)
t.down
t.color('red')
t.write('*****Sandhya*****\n      *Dhana*',move=False,align='center',font=('Arial',13, 'bold'))
t.hideturtle()
